branch-defaults:
  default:
    environment: Labs28-Bridges-TeamA
    group_suffix: null
global:
  application_name: Labs28-Bridges-TeamA
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
